/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.daw1.anxobastosrey.wordle.gui;

/**
 *
 * @author AnxoN
 */
public class AjustesGUIWordle extends javax.swing.JDialog {

    /**
     * Creates new form AjustesGUIWordle
     */
    public AjustesGUIWordle(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJPanel = new javax.swing.JPanel();
        tituloJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ajustesJPanel = new javax.swing.JPanel();
        añadirJPanel = new javax.swing.JPanel();
        insertarJPanel = new javax.swing.JPanel();
        estadoInsertarJPanel = new javax.swing.JPanel();
        borrarJPanel = new javax.swing.JPanel();
        eliminarJPanel = new javax.swing.JPanel();
        estadoEliminarJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mainJPanel.setPreferredSize(new java.awt.Dimension(300, 300));
        mainJPanel.setLayout(new java.awt.BorderLayout());

        tituloJPanel.setMinimumSize(new java.awt.Dimension(100, 100));
        tituloJPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel1.setText("jLabel1");
        tituloJPanel.add(jLabel1);

        jButton1.setText("jButton1");
        tituloJPanel.add(jButton1);

        mainJPanel.add(tituloJPanel, java.awt.BorderLayout.PAGE_START);

        ajustesJPanel.setMinimumSize(new java.awt.Dimension(200, 200));
        ajustesJPanel.setPreferredSize(new java.awt.Dimension(200, 200));
        ajustesJPanel.setLayout(new java.awt.GridLayout(2, 1));

        añadirJPanel.setLayout(new java.awt.GridLayout(2, 1));

        javax.swing.GroupLayout insertarJPanelLayout = new javax.swing.GroupLayout(insertarJPanel);
        insertarJPanel.setLayout(insertarJPanelLayout);
        insertarJPanelLayout.setHorizontalGroup(
            insertarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        insertarJPanelLayout.setVerticalGroup(
            insertarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        añadirJPanel.add(insertarJPanel);

        javax.swing.GroupLayout estadoInsertarJPanelLayout = new javax.swing.GroupLayout(estadoInsertarJPanel);
        estadoInsertarJPanel.setLayout(estadoInsertarJPanelLayout);
        estadoInsertarJPanelLayout.setHorizontalGroup(
            estadoInsertarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        estadoInsertarJPanelLayout.setVerticalGroup(
            estadoInsertarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        añadirJPanel.add(estadoInsertarJPanel);

        ajustesJPanel.add(añadirJPanel);

        borrarJPanel.setLayout(new java.awt.GridLayout(2, 1));

        javax.swing.GroupLayout eliminarJPanelLayout = new javax.swing.GroupLayout(eliminarJPanel);
        eliminarJPanel.setLayout(eliminarJPanelLayout);
        eliminarJPanelLayout.setHorizontalGroup(
            eliminarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        eliminarJPanelLayout.setVerticalGroup(
            eliminarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        borrarJPanel.add(eliminarJPanel);

        javax.swing.GroupLayout estadoEliminarJPanelLayout = new javax.swing.GroupLayout(estadoEliminarJPanel);
        estadoEliminarJPanel.setLayout(estadoEliminarJPanelLayout);
        estadoEliminarJPanelLayout.setHorizontalGroup(
            estadoEliminarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        estadoEliminarJPanelLayout.setVerticalGroup(
            estadoEliminarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        borrarJPanel.add(estadoEliminarJPanel);

        ajustesJPanel.add(borrarJPanel);

        mainJPanel.add(ajustesJPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjustesGUIWordle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjustesGUIWordle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjustesGUIWordle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjustesGUIWordle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AjustesGUIWordle dialog = new AjustesGUIWordle(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ajustesJPanel;
    private javax.swing.JPanel añadirJPanel;
    private javax.swing.JPanel borrarJPanel;
    private javax.swing.JPanel eliminarJPanel;
    private javax.swing.JPanel estadoEliminarJPanel;
    private javax.swing.JPanel estadoInsertarJPanel;
    private javax.swing.JPanel insertarJPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainJPanel;
    private javax.swing.JPanel tituloJPanel;
    // End of variables declaration//GEN-END:variables
}
