/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.daw1.anxobastosrey.wordle.gui;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author AnxoN
 */
public class MainGUIWordle extends javax.swing.JFrame {
    
    private static final java.awt.Color VERDE_LETRAS = new java.awt.Color(102,255,51);
    private static final java.awt.Color AMARILLO_LETRAS = new java.awt.Color(255,204,51);
    private static final java.awt.Color ROJO_LETRAS = new java.awt.Color(255,51,51);
    
    private static final int MAX_INTENTOS = 6;
    private static final int TAMANHO_PALABRA = 5;
    
    private final javax.swing.JLabel[][] labels = new javax.swing.JLabel[MAX_INTENTOS][TAMANHO_PALABRA];

    /**
     * Creates new form MainGUIWordle
     */
    public MainGUIWordle() {
        initComponents();
        rellenarMatrizLabels();
        test();
    }
    
    public void test(){
        for (int i = 0; i < labels.length; i++) {
            JLabel[] label = labels[i];
            for (int j = 0; j < label.length; j++) {
                JLabel jLabel = label[j];
                jLabel.setForeground(ROJO_LETRAS);
                
            }
        }
    }
    
    /*public void test(){
        for (int i = 0; i < labels.length; i++) {
            JLabel[] label = labels[i];
            for (int j = 0; j < label.length; j++) {
                JLabel jLabel = label[j];
                jLabel.setForeground(ROJO_LETRAS);
                
            }
        }
    }
    */
    
    public final void rellenarMatrizLabels(){
        for (int i = 1; i <= MAX_INTENTOS; i++) {
            for (int j = 1; j <= TAMANHO_PALABRA; j++) {
                try {
                    String nombreLabel = "jLabel" + i + "x" + j;
                    javax.swing.JLabel aux = (javax.swing.JLabel) this.getClass().getDeclaredField(nombreLabel).get(this);
                    labels[i-1][j-1] = aux;
                } catch (NoSuchFieldException | SecurityException | IllegalArgumentException | IllegalAccessException ex) {
                    Logger.getLogger(MainGUIWordle.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        temaButtonGroup = new javax.swing.ButtonGroup();
        idiomaButtonGroup = new javax.swing.ButtonGroup();
        mainJPanel = new javax.swing.JPanel();
        letrasJPanel = new javax.swing.JPanel();
        jLabel1x1 = new javax.swing.JLabel();
        jLabel1x2 = new javax.swing.JLabel();
        jLabel1x3 = new javax.swing.JLabel();
        jLabel1x4 = new javax.swing.JLabel();
        jLabel1x5 = new javax.swing.JLabel();
        jLabel2x1 = new javax.swing.JLabel();
        jLabel2x2 = new javax.swing.JLabel();
        jLabel2x3 = new javax.swing.JLabel();
        jLabel2x4 = new javax.swing.JLabel();
        jLabel2x5 = new javax.swing.JLabel();
        jLabel3x1 = new javax.swing.JLabel();
        jLabel3x2 = new javax.swing.JLabel();
        jLabel3x3 = new javax.swing.JLabel();
        jLabel3x4 = new javax.swing.JLabel();
        jLabel3x5 = new javax.swing.JLabel();
        jLabel4x1 = new javax.swing.JLabel();
        jLabel4x2 = new javax.swing.JLabel();
        jLabel4x3 = new javax.swing.JLabel();
        jLabel4x4 = new javax.swing.JLabel();
        jLabel4x5 = new javax.swing.JLabel();
        jLabel5x1 = new javax.swing.JLabel();
        jLabel5x2 = new javax.swing.JLabel();
        jLabel5x3 = new javax.swing.JLabel();
        jLabel5x4 = new javax.swing.JLabel();
        jLabel5x5 = new javax.swing.JLabel();
        jLabel6x1 = new javax.swing.JLabel();
        jLabel6x2 = new javax.swing.JLabel();
        jLabel6x3 = new javax.swing.JLabel();
        jLabel6x4 = new javax.swing.JLabel();
        jLabel6x5 = new javax.swing.JLabel();
        bottomJPanel = new javax.swing.JPanel();
        leftBottomJPanel = new javax.swing.JPanel();
        goodLettersJPanel = new javax.swing.JPanel();
        goodLettersJLabel = new javax.swing.JLabel();
        existsLettersJPanel = new javax.swing.JPanel();
        existsLettersJLabel = new javax.swing.JLabel();
        wrongLettersJPanel = new javax.swing.JPanel();
        wrongLettersJLabel = new javax.swing.JLabel();
        rightBottomJPanel = new javax.swing.JPanel();
        inputJPanel = new javax.swing.JPanel();
        wordTextField = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();
        messagesJPanel = new javax.swing.JPanel();
        messagesJLabel = new javax.swing.JLabel();
        mainJMenuBar = new javax.swing.JMenuBar();
        juegoJMenu = new javax.swing.JMenu();
        temaJMenu = new javax.swing.JMenu();
        temaClaroJRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();
        temaOscuroJRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();
        idiomaJMenu = new javax.swing.JMenu();
        castellanoJRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();
        gallegoJRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();
        inglesJRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();
        francesJRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();
        italianoJRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();
        ajustesJMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DAW1 Wordle AnxoBastosRey");
        setMinimumSize(new java.awt.Dimension(500, 500));

        mainJPanel.setLayout(new java.awt.BorderLayout());

        letrasJPanel.setLayout(new java.awt.GridLayout(6, 5));

        jLabel1x1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1x1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1x1.setText("A");
        jLabel1x1.setToolTipText("");
        letrasJPanel.add(jLabel1x1);

        jLabel1x2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1x2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1x2.setText("A");
        jLabel1x2.setToolTipText("");
        letrasJPanel.add(jLabel1x2);

        jLabel1x3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1x3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1x3.setText("A");
        jLabel1x3.setToolTipText("");
        letrasJPanel.add(jLabel1x3);

        jLabel1x4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1x4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1x4.setText("A");
        jLabel1x4.setToolTipText("");
        letrasJPanel.add(jLabel1x4);

        jLabel1x5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1x5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1x5.setText("A");
        jLabel1x5.setToolTipText("");
        letrasJPanel.add(jLabel1x5);

        jLabel2x1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2x1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2x1.setText("A");
        jLabel2x1.setToolTipText("");
        letrasJPanel.add(jLabel2x1);

        jLabel2x2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2x2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2x2.setText("A");
        jLabel2x2.setToolTipText("");
        letrasJPanel.add(jLabel2x2);

        jLabel2x3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2x3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2x3.setText("A");
        jLabel2x3.setToolTipText("");
        letrasJPanel.add(jLabel2x3);

        jLabel2x4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2x4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2x4.setText("A");
        jLabel2x4.setToolTipText("");
        letrasJPanel.add(jLabel2x4);

        jLabel2x5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2x5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2x5.setText("A");
        jLabel2x5.setToolTipText("");
        letrasJPanel.add(jLabel2x5);

        jLabel3x1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel3x1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3x1.setText("A");
        jLabel3x1.setToolTipText("");
        letrasJPanel.add(jLabel3x1);

        jLabel3x2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel3x2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3x2.setText("A");
        jLabel3x2.setToolTipText("");
        letrasJPanel.add(jLabel3x2);

        jLabel3x3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel3x3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3x3.setText("A");
        jLabel3x3.setToolTipText("");
        letrasJPanel.add(jLabel3x3);

        jLabel3x4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel3x4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3x4.setText("A");
        jLabel3x4.setToolTipText("");
        letrasJPanel.add(jLabel3x4);

        jLabel3x5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel3x5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3x5.setText("A");
        jLabel3x5.setToolTipText("");
        letrasJPanel.add(jLabel3x5);

        jLabel4x1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel4x1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4x1.setText("A");
        jLabel4x1.setToolTipText("");
        letrasJPanel.add(jLabel4x1);

        jLabel4x2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel4x2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4x2.setText("A");
        jLabel4x2.setToolTipText("");
        letrasJPanel.add(jLabel4x2);

        jLabel4x3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel4x3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4x3.setText("A");
        jLabel4x3.setToolTipText("");
        letrasJPanel.add(jLabel4x3);

        jLabel4x4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel4x4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4x4.setText("A");
        jLabel4x4.setToolTipText("");
        letrasJPanel.add(jLabel4x4);

        jLabel4x5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel4x5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4x5.setText("A");
        jLabel4x5.setToolTipText("");
        letrasJPanel.add(jLabel4x5);

        jLabel5x1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel5x1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5x1.setText("A");
        jLabel5x1.setToolTipText("");
        letrasJPanel.add(jLabel5x1);

        jLabel5x2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel5x2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5x2.setText("A");
        jLabel5x2.setToolTipText("");
        letrasJPanel.add(jLabel5x2);

        jLabel5x3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel5x3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5x3.setText("A");
        jLabel5x3.setToolTipText("");
        letrasJPanel.add(jLabel5x3);

        jLabel5x4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel5x4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5x4.setText("A");
        jLabel5x4.setToolTipText("");
        letrasJPanel.add(jLabel5x4);

        jLabel5x5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel5x5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5x5.setText("A");
        jLabel5x5.setToolTipText("");
        letrasJPanel.add(jLabel5x5);

        jLabel6x1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel6x1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6x1.setText("A");
        jLabel6x1.setToolTipText("");
        letrasJPanel.add(jLabel6x1);

        jLabel6x2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel6x2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6x2.setText("A");
        jLabel6x2.setToolTipText("");
        letrasJPanel.add(jLabel6x2);

        jLabel6x3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel6x3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6x3.setText("A");
        jLabel6x3.setToolTipText("");
        letrasJPanel.add(jLabel6x3);

        jLabel6x4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel6x4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6x4.setText("A");
        jLabel6x4.setToolTipText("");
        letrasJPanel.add(jLabel6x4);

        jLabel6x5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel6x5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6x5.setText("A");
        jLabel6x5.setToolTipText("");
        letrasJPanel.add(jLabel6x5);

        mainJPanel.add(letrasJPanel, java.awt.BorderLayout.CENTER);

        bottomJPanel.setPreferredSize(new java.awt.Dimension(200, 100));
        bottomJPanel.setLayout(new java.awt.GridLayout(1, 2));

        leftBottomJPanel.setLayout(new java.awt.GridLayout(3, 1));

        goodLettersJPanel.setLayout(new java.awt.GridLayout(1, 0));

        goodLettersJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        goodLettersJLabel.setForeground(new java.awt.Color(102, 255, 51));
        goodLettersJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        goodLettersJLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        goodLettersJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        goodLettersJLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        goodLettersJPanel.add(goodLettersJLabel);

        leftBottomJPanel.add(goodLettersJPanel);

        existsLettersJPanel.setLayout(new java.awt.GridLayout(1, 0));

        existsLettersJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        existsLettersJLabel.setForeground(new java.awt.Color(255, 204, 51));
        existsLettersJPanel.add(existsLettersJLabel);

        leftBottomJPanel.add(existsLettersJPanel);

        wrongLettersJPanel.setLayout(new java.awt.GridLayout(1, 0));

        wrongLettersJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        wrongLettersJLabel.setForeground(new java.awt.Color(255, 51, 51));
        wrongLettersJPanel.add(wrongLettersJLabel);

        leftBottomJPanel.add(wrongLettersJPanel);

        bottomJPanel.add(leftBottomJPanel);

        rightBottomJPanel.setLayout(new java.awt.GridLayout(2, 1));

        wordTextField.setMinimumSize(new java.awt.Dimension(120, 22));
        wordTextField.setPreferredSize(new java.awt.Dimension(120, 22));
        inputJPanel.add(wordTextField);

        sendButton.setText("Enviar");
        inputJPanel.add(sendButton);

        rightBottomJPanel.add(inputJPanel);

        messagesJPanel.setLayout(new java.awt.GridLayout(1, 1));

        messagesJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        messagesJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messagesJPanel.add(messagesJLabel);

        rightBottomJPanel.add(messagesJPanel);

        bottomJPanel.add(rightBottomJPanel);

        mainJPanel.add(bottomJPanel, java.awt.BorderLayout.PAGE_END);

        juegoJMenu.setText("Juego");
        mainJMenuBar.add(juegoJMenu);

        temaJMenu.setText("Tema");

        temaButtonGroup.add(temaClaroJRadioButtonMenuItem);
        temaClaroJRadioButtonMenuItem.setSelected(true);
        temaClaroJRadioButtonMenuItem.setText("Claro");
        temaJMenu.add(temaClaroJRadioButtonMenuItem);

        temaButtonGroup.add(temaOscuroJRadioButtonMenuItem);
        temaOscuroJRadioButtonMenuItem.setText("Oscuro");
        temaJMenu.add(temaOscuroJRadioButtonMenuItem);

        mainJMenuBar.add(temaJMenu);

        idiomaJMenu.setText("Idioma");

        idiomaButtonGroup.add(castellanoJRadioButtonMenuItem);
        castellanoJRadioButtonMenuItem.setSelected(true);
        castellanoJRadioButtonMenuItem.setText("Castellano");
        idiomaJMenu.add(castellanoJRadioButtonMenuItem);

        idiomaButtonGroup.add(gallegoJRadioButtonMenuItem);
        gallegoJRadioButtonMenuItem.setText("Gallego");
        idiomaJMenu.add(gallegoJRadioButtonMenuItem);

        idiomaButtonGroup.add(inglesJRadioButtonMenuItem);
        inglesJRadioButtonMenuItem.setText("Ingles");
        idiomaJMenu.add(inglesJRadioButtonMenuItem);

        idiomaButtonGroup.add(francesJRadioButtonMenuItem);
        francesJRadioButtonMenuItem.setText("Frances");
        idiomaJMenu.add(francesJRadioButtonMenuItem);

        idiomaButtonGroup.add(italianoJRadioButtonMenuItem);
        italianoJRadioButtonMenuItem.setText("Italiano");
        idiomaJMenu.add(italianoJRadioButtonMenuItem);

        mainJMenuBar.add(idiomaJMenu);

        ajustesJMenu.setText("Ajustes");
        mainJMenuBar.add(ajustesJMenu);

        setJMenuBar(mainJMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUIWordle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUIWordle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUIWordle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUIWordle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUIWordle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ajustesJMenu;
    private javax.swing.JPanel bottomJPanel;
    private javax.swing.JRadioButtonMenuItem castellanoJRadioButtonMenuItem;
    private javax.swing.JLabel existsLettersJLabel;
    private javax.swing.JPanel existsLettersJPanel;
    private javax.swing.JRadioButtonMenuItem francesJRadioButtonMenuItem;
    private javax.swing.JRadioButtonMenuItem gallegoJRadioButtonMenuItem;
    private javax.swing.JLabel goodLettersJLabel;
    private javax.swing.JPanel goodLettersJPanel;
    private javax.swing.ButtonGroup idiomaButtonGroup;
    private javax.swing.JMenu idiomaJMenu;
    private javax.swing.JRadioButtonMenuItem inglesJRadioButtonMenuItem;
    private javax.swing.JPanel inputJPanel;
    private javax.swing.JRadioButtonMenuItem italianoJRadioButtonMenuItem;
    private javax.swing.JLabel jLabel1x1;
    private javax.swing.JLabel jLabel1x2;
    private javax.swing.JLabel jLabel1x3;
    private javax.swing.JLabel jLabel1x4;
    private javax.swing.JLabel jLabel1x5;
    private javax.swing.JLabel jLabel2x1;
    private javax.swing.JLabel jLabel2x2;
    private javax.swing.JLabel jLabel2x3;
    private javax.swing.JLabel jLabel2x4;
    private javax.swing.JLabel jLabel2x5;
    private javax.swing.JLabel jLabel3x1;
    private javax.swing.JLabel jLabel3x2;
    private javax.swing.JLabel jLabel3x3;
    private javax.swing.JLabel jLabel3x4;
    private javax.swing.JLabel jLabel3x5;
    private javax.swing.JLabel jLabel4x1;
    private javax.swing.JLabel jLabel4x2;
    private javax.swing.JLabel jLabel4x3;
    private javax.swing.JLabel jLabel4x4;
    private javax.swing.JLabel jLabel4x5;
    private javax.swing.JLabel jLabel5x1;
    private javax.swing.JLabel jLabel5x2;
    private javax.swing.JLabel jLabel5x3;
    private javax.swing.JLabel jLabel5x4;
    private javax.swing.JLabel jLabel5x5;
    private javax.swing.JLabel jLabel6x1;
    private javax.swing.JLabel jLabel6x2;
    private javax.swing.JLabel jLabel6x3;
    private javax.swing.JLabel jLabel6x4;
    private javax.swing.JLabel jLabel6x5;
    private javax.swing.JMenu juegoJMenu;
    private javax.swing.JPanel leftBottomJPanel;
    private javax.swing.JPanel letrasJPanel;
    private javax.swing.JMenuBar mainJMenuBar;
    private javax.swing.JPanel mainJPanel;
    private javax.swing.JLabel messagesJLabel;
    private javax.swing.JPanel messagesJPanel;
    private javax.swing.JPanel rightBottomJPanel;
    private javax.swing.JButton sendButton;
    private javax.swing.ButtonGroup temaButtonGroup;
    private javax.swing.JRadioButtonMenuItem temaClaroJRadioButtonMenuItem;
    private javax.swing.JMenu temaJMenu;
    private javax.swing.JRadioButtonMenuItem temaOscuroJRadioButtonMenuItem;
    private javax.swing.JTextField wordTextField;
    private javax.swing.JLabel wrongLettersJLabel;
    private javax.swing.JPanel wrongLettersJPanel;
    // End of variables declaration//GEN-END:variables
}
