/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.daw1.anxobastosrey.wordle.gui;

/**
 *
 * @author AnxoN
 */
public class MainGUIWordle extends javax.swing.JFrame {

    /**
     * Creates new form MainGUIWordle
     */
    public MainGUIWordle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJPanel = new javax.swing.JPanel();
        letrasJPanel = new javax.swing.JPanel();
        jLabel1x1 = new javax.swing.JLabel();
        jLabel1x2 = new javax.swing.JLabel();
        jLabel1x3 = new javax.swing.JLabel();
        jLabel1x4 = new javax.swing.JLabel();
        jLabel1x5 = new javax.swing.JLabel();
        jLabel2x1 = new javax.swing.JLabel();
        jLabel2x2 = new javax.swing.JLabel();
        jLabel2x3 = new javax.swing.JLabel();
        jLabel2x4 = new javax.swing.JLabel();
        jLabel2x5 = new javax.swing.JLabel();
        jLabel3x1 = new javax.swing.JLabel();
        jLabel3x2 = new javax.swing.JLabel();
        jLabel3x3 = new javax.swing.JLabel();
        jLabel3x4 = new javax.swing.JLabel();
        jLabel3x5 = new javax.swing.JLabel();
        jLabel4x1 = new javax.swing.JLabel();
        jLabel4x2 = new javax.swing.JLabel();
        jLabel4x3 = new javax.swing.JLabel();
        jLabel4x4 = new javax.swing.JLabel();
        jLabel4x5 = new javax.swing.JLabel();
        jLabel5x1 = new javax.swing.JLabel();
        jLabel5x2 = new javax.swing.JLabel();
        jLabel5x3 = new javax.swing.JLabel();
        jLabel5x4 = new javax.swing.JLabel();
        jLabel5x5 = new javax.swing.JLabel();
        jLabel6x1 = new javax.swing.JLabel();
        jLabel6x2 = new javax.swing.JLabel();
        jLabel6x3 = new javax.swing.JLabel();
        jLabel6x4 = new javax.swing.JLabel();
        jLabel6x5 = new javax.swing.JLabel();
        bottomJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DAW1 Wordle AnxoBastosRey");

        mainJPanel.setLayout(new java.awt.BorderLayout());

        letrasJPanel.setLayout(new java.awt.GridLayout(6, 5));

        jLabel1x1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1x1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1x1.setText("A");
        jLabel1x1.setToolTipText("");
        letrasJPanel.add(jLabel1x1);

        jLabel1x2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1x2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1x2.setText("A");
        jLabel1x2.setToolTipText("");
        letrasJPanel.add(jLabel1x2);

        jLabel1x3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1x3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1x3.setText("A");
        jLabel1x3.setToolTipText("");
        letrasJPanel.add(jLabel1x3);

        jLabel1x4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1x4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1x4.setText("A");
        jLabel1x4.setToolTipText("");
        letrasJPanel.add(jLabel1x4);

        jLabel1x5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1x5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1x5.setText("A");
        jLabel1x5.setToolTipText("");
        letrasJPanel.add(jLabel1x5);

        jLabel2x1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2x1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2x1.setText("A");
        jLabel2x1.setToolTipText("");
        letrasJPanel.add(jLabel2x1);

        jLabel2x2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2x2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2x2.setText("A");
        jLabel2x2.setToolTipText("");
        letrasJPanel.add(jLabel2x2);

        jLabel2x3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2x3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2x3.setText("A");
        jLabel2x3.setToolTipText("");
        letrasJPanel.add(jLabel2x3);

        jLabel2x4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2x4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2x4.setText("A");
        jLabel2x4.setToolTipText("");
        letrasJPanel.add(jLabel2x4);

        jLabel2x5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2x5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2x5.setText("A");
        jLabel2x5.setToolTipText("");
        letrasJPanel.add(jLabel2x5);

        jLabel3x1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel3x1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3x1.setText("A");
        jLabel3x1.setToolTipText("");
        letrasJPanel.add(jLabel3x1);

        jLabel3x2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel3x2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3x2.setText("A");
        jLabel3x2.setToolTipText("");
        letrasJPanel.add(jLabel3x2);

        jLabel3x3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel3x3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3x3.setText("A");
        jLabel3x3.setToolTipText("");
        letrasJPanel.add(jLabel3x3);

        jLabel3x4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel3x4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3x4.setText("A");
        jLabel3x4.setToolTipText("");
        letrasJPanel.add(jLabel3x4);

        jLabel3x5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel3x5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3x5.setText("A");
        jLabel3x5.setToolTipText("");
        letrasJPanel.add(jLabel3x5);

        jLabel4x1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel4x1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4x1.setText("A");
        jLabel4x1.setToolTipText("");
        letrasJPanel.add(jLabel4x1);

        jLabel4x2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel4x2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4x2.setText("A");
        jLabel4x2.setToolTipText("");
        letrasJPanel.add(jLabel4x2);

        jLabel4x3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel4x3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4x3.setText("A");
        jLabel4x3.setToolTipText("");
        letrasJPanel.add(jLabel4x3);

        jLabel4x4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel4x4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4x4.setText("A");
        jLabel4x4.setToolTipText("");
        letrasJPanel.add(jLabel4x4);

        jLabel4x5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel4x5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4x5.setText("A");
        jLabel4x5.setToolTipText("");
        letrasJPanel.add(jLabel4x5);

        jLabel5x1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel5x1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5x1.setText("A");
        jLabel5x1.setToolTipText("");
        letrasJPanel.add(jLabel5x1);

        jLabel5x2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel5x2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5x2.setText("A");
        jLabel5x2.setToolTipText("");
        letrasJPanel.add(jLabel5x2);

        jLabel5x3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel5x3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5x3.setText("A");
        jLabel5x3.setToolTipText("");
        letrasJPanel.add(jLabel5x3);

        jLabel5x4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel5x4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5x4.setText("A");
        jLabel5x4.setToolTipText("");
        letrasJPanel.add(jLabel5x4);

        jLabel5x5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel5x5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5x5.setText("A");
        jLabel5x5.setToolTipText("");
        letrasJPanel.add(jLabel5x5);

        jLabel6x1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel6x1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6x1.setText("A");
        jLabel6x1.setToolTipText("");
        letrasJPanel.add(jLabel6x1);

        jLabel6x2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel6x2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6x2.setText("A");
        jLabel6x2.setToolTipText("");
        letrasJPanel.add(jLabel6x2);

        jLabel6x3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel6x3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6x3.setText("A");
        jLabel6x3.setToolTipText("");
        letrasJPanel.add(jLabel6x3);

        jLabel6x4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel6x4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6x4.setText("A");
        jLabel6x4.setToolTipText("");
        letrasJPanel.add(jLabel6x4);

        jLabel6x5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel6x5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6x5.setText("A");
        jLabel6x5.setToolTipText("");
        letrasJPanel.add(jLabel6x5);

        mainJPanel.add(letrasJPanel, java.awt.BorderLayout.CENTER);

        bottomJPanel.setPreferredSize(new java.awt.Dimension(200, 100));
        bottomJPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        mainJPanel.add(bottomJPanel, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUIWordle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUIWordle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUIWordle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUIWordle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUIWordle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomJPanel;
    private javax.swing.JLabel jLabel1x1;
    private javax.swing.JLabel jLabel1x2;
    private javax.swing.JLabel jLabel1x3;
    private javax.swing.JLabel jLabel1x4;
    private javax.swing.JLabel jLabel1x5;
    private javax.swing.JLabel jLabel2x1;
    private javax.swing.JLabel jLabel2x2;
    private javax.swing.JLabel jLabel2x3;
    private javax.swing.JLabel jLabel2x4;
    private javax.swing.JLabel jLabel2x5;
    private javax.swing.JLabel jLabel3x1;
    private javax.swing.JLabel jLabel3x2;
    private javax.swing.JLabel jLabel3x3;
    private javax.swing.JLabel jLabel3x4;
    private javax.swing.JLabel jLabel3x5;
    private javax.swing.JLabel jLabel4x1;
    private javax.swing.JLabel jLabel4x2;
    private javax.swing.JLabel jLabel4x3;
    private javax.swing.JLabel jLabel4x4;
    private javax.swing.JLabel jLabel4x5;
    private javax.swing.JLabel jLabel5x1;
    private javax.swing.JLabel jLabel5x2;
    private javax.swing.JLabel jLabel5x3;
    private javax.swing.JLabel jLabel5x4;
    private javax.swing.JLabel jLabel5x5;
    private javax.swing.JLabel jLabel6x1;
    private javax.swing.JLabel jLabel6x2;
    private javax.swing.JLabel jLabel6x3;
    private javax.swing.JLabel jLabel6x4;
    private javax.swing.JLabel jLabel6x5;
    private javax.swing.JPanel letrasJPanel;
    private javax.swing.JPanel mainJPanel;
    // End of variables declaration//GEN-END:variables
}
